[package]
name = "seaply-client"
version = "0.1.0"
description = "Seaply 客服工作台（桌面客户端）"
edition = "2021"

[lib]
name = "seaply_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"
